### ISSUE TITLE
"Internal Server Error" after click to "Google Login"

### ISSUE THREAD

**Issue by mpiascik** [rggibson/Authtopus#3]
Issue exists on both local deployment and appengine (https://authtopus.appspot.com)

**Comment by rggibson** [comment]
Looks like it's a bug caused by some non-ascii characters in the response from the Google login.  Here's the stack trace:

```
2015-11-26 10:06:30.157
Encountered unexpected error from ProtoRPC method implementation: UnicodeDecodeError ('ascii' codec can't decode byte 0xc5 in position 115: ordinal not in range(128))
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
    response = method(instance, request)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/endpoints-1.0/endpoints/api_config.py", line 1332, in invoke_remote
    return remote_method(service_instance, request)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/protorpc-1.0/protorpc/remote.py", line 414, in invoke_remote_method
    response = method(service_instance, request)
  File "/base/data/home/apps/s~authtopus/1.388833677725947918/ext/endpoints_proto_datastore/endpoints_proto_datastore/ndb/model.py", line 1412, in EntityToRequestMethod
    response = api_method(service_instance, request)
  File "/base/data/home/apps/s~authtopus/1.388833677725947918/ext/authtopus/authtopus/api.py", line 490, in SocialLogin
    logging.debug( slm.provider + ' response: ' + str( result.content ) )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 115: ordinal not in range(128)
```

I'll look at it a bit more when I get the chance.

**Comment by rggibson** [comment]
I should also mention that it works fine for me, so there's something unique in your Google public profile information that's triggering the problem.  Might be able to get around it by just removing the offending logging.debug( ) line.

**Comment by rggibson** [comment]
OK, I've updated the library and the example app.  If it's not too much hassle, can you try another Google login and let me know if it works?

**Comment by mpiascik** [comment]
Now it works fine, I've checked with two different google accounts. Thanks!

**Comment by rggibson** [comment]
Awesome, thanks for checking!
